server:
  port: 8082
spring:
  application:
    name: flight-booking-service
  datasource:
    url: jdbc:postgresql://localhost:5433/booking_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
resilience4j:
  ratelimiter:
    instances:
      bookingApi:
        limitForPeriod: 5
        limitRefreshPeriod: 10m
        timeoutDuration: 0s
  circuitbreaker:
    instances:
      paymentService:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
