spring:
  application:
    name: flight-booking-service

  # datasource config...
  datasource:
    url: jdbc:postgresql://localhost:5433/flight_booking
    username: postgres
    password: postgres

server:
  port: 8082

# Eureka Client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

# Docker profile
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://booking-db:5433/flight_booking

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/