server:
  port: 8083
spring:
  application:
    name: flight-payment-service
  datasource:
    url: jdbc:postgresql://localhost:5434/payment_db
    username: user
    password: password
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
